batch_size: 128
data_root: /mnt/class_data/group4/talen/
device: cuda
image_size:
- 224
- 224
learning_rate: 0.0018
num_classes: 2
num_epochs: 150
num_workers: 4
seed: 32678456782
weight_decay: 0.0001
