_wandb:
    value:
        cli_version: 0.19.2
        m: []
        python_version: 3.9.21
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.9.21
            "5": 0.19.2
            "8":
                - 5
            "12": 0.19.2
            "13": linux-x86_64
batch_size:
    value: 128
data_root:
    value: /mnt/class_data/group4/talen/
device:
    value: cuda
image_size:
    value:
        - 224
        - 224
learning_rate:
    value: 0.0018
num_classes:
    value: 2
num_epochs:
    value: 150
num_workers:
    value: 4
only_validate:
    value: false
resume_path:
    value: /home/Talen/foragefish_classifier/model_states_2025-01-18_11-59-18/best.pt
seed:
    value: 32678456782
weight_decay:
    value: 0.0001
