batch_size: 16
data_root: /mnt/class_data/group4/talen/
device: cuda
image_size:
- 224
- 224
learning_rate: 0.0018
num_classes: 2
num_epochs: 150
num_workers: 4
only_validate: false
resume_path: /home/Talen/foragefish_classifier/model_states_2025-01-18_11-59-18/best.pt
seed: 32678456782
weight_decay: 0.0001
